version: '3.8'
services:
  db:
    image: postgres:9.6
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=2967
      - POSTGRES_USER=postgres
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb -e production"
    volumes:
      - .:/expenses
      - tmp:/expenses/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build: nginx
    volumes:
      - tmp:/expenses/tmp
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  tmp:
  db-data:
